apiVersion: v1
kind: ServiceAccount #kubestate service account
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.2.3
  name: kube-state-metrics
  namespace: kube-system
