apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
spec:
  selector:
    app: prometheus-server
  type: NodePort
  ports:
    - port: 9090 #8080 previously
      targetPort: 9090
      nodePort: 30000 #exposes prometheus on all k8 node IPs on port 30000
